### ISSUE TITLE
Return an error when the branch exists but the start point does not

### ISSUE THREAD

**Issue by glevco** [bencherdev/bencher#482] opened 2024-08-21 00:40 UTC
I accidentally introduced a regression in my CI that made the `main` (base branch) benchmark stop working. In other words, the most recent commit on `main` did not publish any reports to Bencher.

Then, every open PR that uses `main` as the Start Point, with its most recent commit as the Start Point SHA, fails to copy metrics/thresholds. This means that every PR will always pass the CI check, because without thresholds no alerts are generated. We do get a comment from Bencher warning that no threshold is set. However, I think a better behavior would be to either:

1. Use metrics/thresholds from a working parent commit of the Start Point (maybe not so good and also more complicated);
2. The check for PRs should fail when the Start Point is missing reports (metrics? not sure on the correct term).

**Comment by epompeii** [comment] 2024-08-21 01:52
Well everything seems to be working as expected after "fallible start points" was implemented: https://github.com/bencherdev/bencher/issues/450

From the updated docs for [`--branch-start-point`](https://bencher.dev/docs/explanation/branch-selection/#--branch-start-point-branch):

> - If `branch` does not exist and the Start Point does not exist, then the branch will be created without any historical data.
> - If `branch` does exist and the Start Point does not exist, then this option is ignored.

From the updated docs for [`--branch-start-point-hash`](https://bencher.dev/docs/explanation/branch-selection/#--branch-start-point-hash-hash):

> - If `branch` does not exist and the `branch-start-point` does not exist at the specified hash, then the branch will be created without any historical data.
> - If `branch` does exist and the `branch-start-point` does not exist at the specified hash, then this option is ignored.

This was the fundamental tradeoff made to allow both a base branch and a PR Bencher workflow to be added as a part of a single PR. My original thinking was that a missing Start Point should be a hard error (to prevent what you are running into now). However, you and others were running into a catch 22 when adding Bencher to a project in a single PR, which requires fallible Start Points to solve. I ended up coming down on the side of making onboarding easier and thus making Start Points fallible.

**Comment by glevco** [comment] 2024-08-21 02:49
@epompeii Got it, what an irony that the feature that I requested is what's causing this new problem 🥲

What if you used the existence of the `start-point` to switch on that behavior? I mean, when neither the `branch`, nor the `start-point`, nor the `start-point-hash` exist, it must be an onboarding and you should proceed as it is (without historical data).

However, if the `start-point` does exist (that is, the base branch), then the `start-point-hash` must exist too (if it's set). This would cover the case I ran into, as the `start-point` existed, but not the `start-point-hash`. Then, Bencher should error and fail the CI. Would that make sense? Maybe I'm missing other edge cases that are not in my mind.

BTW only kind of related, but it's not completely clear to me from the docs why both `start-point` and `start-point-hash` exist.

Thanks!

**Comment by epompeii** [comment] 2024-08-21 16:33
> What if you used the existence of the `start-point` to switch on that behavior? I mean, when neither the `branch`, nor the `start-point`, nor the `start-point-hash` exist, it must be an onboarding and you should proceed as it is (without historical data).
> 
> However, if the `start-point` does exist (that is, the base branch), then the `start-point-hash` must exist too (if it's set). This would cover the case I ran into, as the `start-point` existed, but not the `start-point-hash`. Then, Bencher should error and fail the CI. Would that make sense? Maybe I'm missing other edge cases that are not in my mind.

Yes, I believe this would work. However, the hang up for me is the "switching" of behavior. I'm worried that this would cause confusion for users. That is, running the same `bencher run` command twice and getting very different results is rather unexpected behavior.

```
bencher run --project my-project --branch test-branch --branch-start-point base "bencher mock"
```

On the first run this would pass, but on the second run this would fail.

I'm going to close this as not planned for now. If I see more users running into this error, I'm open to reconsidering this decision in the future.

**Closed by epompeii** 2024-08-21 16:33 UTC

**Comment by epompeii** [comment] 2024-08-21 16:48
> BTW only kind of related, but it's not completely clear to me from the docs why both `start-point` and `start-point-hash` exist.

Over time, there is a many-to-many relationship between git branches and git hashes. Therefore Bencher needs to always know the Branch, the hash is not sufficient.

Adding the git hash allows for tracking rebases. This is what the example in the docs is trying to show: https://bencher.dev/docs/explanation/branch-selection/#--branch-start-point-hash-hash

Let me know if I can help clarify anything further though.
